@startuml
left to right direction
Biblioteca "1" *-- "n" Libro : contiene
Biblioteca <|-- Paiba
Biblioteca <|-- Artes
Biblioteca <|-- Ingenieria
Libro -- Usuario
class Libro{
    nombre
    autor
    biblioteca
    prestado : bool
    historicoUsuarios
    asignar_biblioteca()
    asignar_nombre()
    asignar_autor()
    entregar_biblioteca()
    entregar_nombre()
    entregar_autor()
    entregar_estado()
    cambiar_estado()
}

class Biblioteca{
    nombre
    libros
    txt
    buscador
    leer_libros()
}

Usuario <|-- Admin
Usuario <|-- Estudiante
Usuario <|-- Docente
class Usuario{
    cargo
    sede
    carrera
    nombre
    documento
    asignar_sede()
    asignar_carrera()
    asignar_nombre()
    asignar_documento()
    entregar_cargo()
    entregar_sede()
    entregar_carrera()
    entregar_nombre()
    entregar_documento()
    llenar_usuario()
}

Biblioteca "1" *-- "1" BuscadorLibros:contiene
SistemaBibliotecas "1" *-- "1" Usuario:contiene
SistemaBibliotecas "1" *-- "n" Biblioteca:contiene
class BuscadorLibros{
    librosEncontrados
    por_autor(Biblioteca, autor)
    por_libro(Biblioteca, nombre)
    por_biblioteca(Biblioteca)
    limpiar_librosEncontrados()
    entregar_librosEncontrados()
}

class SistemaBibliotecas{
    iniciar_sesion()
    
}
@enduml